import "../styles/globals.css";
import Head from "next/head";
import store from "store";
import { StoreProvider } from "easy-peasy";

function MyApp({ Component, pageProps }) {
  return (
    <StoreProvider store={store}>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </StoreProvider>
  );
}

export default MyApp;
